# Pololu based motors

neck_yaw_joint:
  pololu_id: 12
  motor_id: 5
  init: 0.0
  min: -45.0
  max: 45.0
  reverse: false
  calibration:
    min_pulse: 1000
    min_angle: -45
    max_pulse: 2000
    max_angle: 45

neck_pitch_joint:
  pololu_id: 12
  motor_id: 0
  init: 0.0
  min: -50.0
  max: 50.0
  reverse: true
  calibration:
    min_pulse: 1000
    min_angle: -50
    max_pulse: 2000
    max_angle: 50

jaw_joint:
  pololu_id: 12
  motor_id: 1
  init: -50.0
  min: 0.0
  max: 100.0
  reverse: false
  calibration:
    min_pulse: 1000
    min_angle: -50
    max_pulse: 2000
    max_angle: 50

smile_joint:
  pololu_id: 12
  motor_id: 2
  init: 0.0
  min: -55.0
  max: 55.0
  reverse: true
  calibration:
    min_pulse: 1000
    min_angle: -55
    max_pulse: 2000
    max_angle: 55

brow_joint:
  pololu_id: 12
  motor_id: 3
  init: -25
  min: -24.0
  max: 50.0
  reverse: true
  calibration:
    min_pulse: 1000
    min_angle: -50
    max_pulse: 2000
    max_angle: 50





