# Pololu based motors

neck_yaw_joint:
  pololu_id: 12
  motor_id: 5
  min: 1000
  init: 1500
  max: 2000
  reverse: false
  calibration:
    min_pulse: 1000
    min_angle: -45
    max_pulse: 2000
    max_angle: 45

camera_joint:
  pololu_id: 12
  motor_id: 6
  min: 1000
  init: 1296
  max: 1840
  reverse: true
  calibration:
    min_pulse: 1000
    min_angle: -50
    max_pulse: 2000
    max_angle: 50

neck_pitch_joint:
  pololu_id: 12
  motor_id: 0
  min: 1285
  init: 1657
  max: 2000
  reverse: true
  calibration:
    min_pulse: 1000
    min_angle: -50
    max_pulse: 2000
    max_angle: 50

jaw_joint:
  pololu_id: 12
  motor_id: 1
  min: 1000
  init: 1001
  max: 2000
  reverse: false
  calibration:
    min_pulse: 1000
    min_angle: -50
    max_pulse: 2000
    max_angle: 50

smile_joint:
  pololu_id: 12
  motor_id: 2
  min: 1000
  init: 1510
  max: 2000
  reverse: true
  calibration:
    min_pulse: 1000
    min_angle: -55
    max_pulse: 2000
    max_angle: 55

brow_joint:
  pololu_id: 12
  motor_id: 3
  min: 1000
  init: 1207
  max: 1522
  reverse: true
  calibration:
    min_pulse: 1000
    min_angle: -50
    max_pulse: 2000
    max_angle: 50





